name: Ruby Testing
on: [pull_request]
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.1
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true
      - name: Prepare test env
        run: |
          bundle exec rake db:create
          bundle exec rake db:migrate
          bundle exec rake db:test:prepare
      - name: Run tests
        run: bundle exec rake test