name: Ruby Testing
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.1
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true

      - name: Install dependent libraries
        run: sudo apt-get -yqq install libpq-dev

      - name: Bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Setup Database
        env:
            DATABASE_URL: postgres://postgres:@localhost:5432/test
            RAILS_ENV: test
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        run: |
          bundle exec rake db:create
          bundle exec rails db:migrate
          RAILS_ENV=test bundle exec rake

      # - name: Run tests
      #   run: bundle exec rake test